// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: ElecrowScreen

#include "ui.h"
#include "config.h"
// const uint16_t RPM_DISPLAY_MIN = 0;     // Minimum RPM value that can be shown on the slider.
// const uint16_t RPM_DISPLAY_MAX = 900;   // Maximum RPM value that can be shown on the slider.
const float OLD_RANGE = RPM_DISPLAY_MAX - RPM_DISPLAY_MIN;
const float NEW_RANGE = 800;
const float MULTIPLIER = NEW_RANGE / OLD_RANGE;
const int OFFSET = 400;

const int greenWidth = (RPM_MAX - RPM_MIN) * MULTIPLIER;
const int greenX = (MULTIPLIER * RPM_MIN) + (greenWidth/2) - OFFSET;

const int blueWidth = (RPM_MIN - RPM_DISPLAY_MIN) * MULTIPLIER;
const int blueX = (MULTIPLIER * RPM_DISPLAY_MIN) + (blueWidth/2) - OFFSET;

const int redWidth = (RPM_DISPLAY_MAX - RPM_MAX) * MULTIPLIER;
const int redX = (MULTIPLIER * RPM_MAX) + (redWidth/2) - OFFSET;

const int y_value = (BAR_HEIGHT / 2) - 240;
const int bar_ratio = 0.8;

// const uint16_t MID_RANGE = RANGE / 2 - 400;

// //message Ethan or David to get the red and blue to line up with shifting.
// const uint16_t RPM_MIN = 225;     // Starts flashing when RPM drops *below* this value (shift down).
// const uint16_t RPM_MAX = 675;     // Starts flashing when RPM exceeds *above* this value (shift up).

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_geardu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_geardu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_geardu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_geardu, 0);
    lv_obj_set_y(ui_geardu, -40);
    lv_obj_set_align(ui_geardu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_geardu, "Gear");
    lv_obj_set_style_text_font(ui_geardu, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_egear = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_egear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_egear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_egear, 0);
    lv_obj_set_y(ui_egear, 90);
    lv_obj_set_align(ui_egear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_egear, "U");
    lv_obj_set_style_text_font(ui_egear, &ui_font_Font250, LV_PART_MAIN | LV_STATE_DEFAULT);
}